In [23]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [24]:
arr = np.array((1,2,3,4,5,6,7))
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [25]:
#0 dimention Array
arr = np.array((111))
print((arr))
print(arr.ndim)

111
0


In [26]:
# 1 dimention Array
arr = np.array((1,12,15,11))
print((arr))
print(arr.ndim)

[ 1 12 15 11]
1


In [27]:
# 2 dimention Array
arr = np.array([[1,12,15,11],[10,20,30,40]])
print((arr))
print(arr.ndim)

[[ 1 12 15 11]
 [10 20 30 40]]
2


In [28]:
# 2 dimention Array
arr = np.array([[1,12,15,11],[10,20,30,40],[12,30,52,62]])
print((arr))
print(arr.ndim)

[[ 1 12 15 11]
 [10 20 30 40]
 [12 30 52 62]]
2


In [29]:
# 3 dimention Array
arr = np.array([[[10,10,20],[10,20,30]]])
print((arr))
print(arr.ndim)

[[[10 10 20]
  [10 20 30]]]
3


In [30]:
# 5 dimention array


arr = np.array([1,2,5,6,34,7],ndmin= 5)
print(arr)
print("number of dimention", arr.ndim)

[[[[[ 1  2  5  6 34  7]]]]]
number of dimention 5


numpy array indexing


In [31]:
arr = np.array((1,2,3,4,5,6,7))
print(type(arr))
print(arr[1])

<class 'numpy.ndarray'>
2


# add the element from the array

In [34]:
arr = np.array([1,2,56,3,6,98,5,5,6,7])

print("add elemnt no. 5",arr[5] )
print("add elemnt no. 8",arr[8] )
print("add elemnt no. 3",arr[3] )
print("add elemnt no. 7",arr[7] )
print("total of all the elements ",arr[5]+arr[8]+arr[3]+arr[7])

add elemnt no. 5 98
add elemnt no. 8 6
add elemnt no. 3 3
add elemnt no. 7 5
total of all the elements  112


slicing of numpy array

In [43]:
#one dimention
arr = np.array([1,2,56,3,6,98,5,5,6,7])
print(arr[1:5])
print(arr.ndim)
print(type(arr))

print(arr[::3]) #skip 3 elements

[ 2 56  3  6]
1
<class 'numpy.ndarray'>
[1 3 5 7]


In [45]:
# two dimention
arr = np.array([[1,2,56,3,6,98,5,5,6,7],[10,20,5,2,6,56,7,5,8,9]])
print(arr[1:5])
print(arr.ndim)
print(type(arr))


print(arr[0,1:4]) # 0 array , index number 1 to 4
print(arr[1,1:4]) # 1 array , index number 1 to 4



[[10 20  5  2  6 56  7  5  8  9]]
2
<class 'numpy.ndarray'>
[ 2 56  3]
[20  5  2]


cheking the data type of an array

In [46]:
arr  = np.array([1,2,5,6,0])
print (arr.dtype)

int32


In [47]:
arr  = np.array(['cat','dog'])
print (arr.dtype)

<U3


creating array using diffrent type of datatypes

In [50]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


Print Shape of 2D array


In [51]:
arr = np.array([[[1,2,3],[5,6,3],[4,8,9]]])
print(arr.shape)

#output
# 1 = how many 2D 
# 3 = the total rows
# 3 = the total items in each rows

(1, 3, 3)


joining numpy arrays

In [54]:
#join for 1D 
arr1 = np.array([10,20,30])
arr2 = np.array([110,240,350])

arr3 = np.concatenate((arr1,arr2))
print(arr3)

[ 10  20  30 110 240 350]


In [61]:
#join for 2d array

arr1 = np.array([[10,20,30],[10,52,85]])
arr2 = np.array([[10,20,30],[10,52,85]])

arr3 = np.concatenate((arr1,arr2),axis = 1)
print(arr3)
print(type(arr3))

[[10 20 30 10 20 30]
 [10 52 85 10 52 85]]
<class 'numpy.ndarray'>
